[font]
size = 17

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[colors.primary]
background = "#161616"
foreground = "#ffffff"

[colors.search.matches]
foreground = "CellBackground"
background = "#ee5396"

[colors.footer_bar]
background = "#262626"
foreground = "#ffffff"

[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"

